const Groq = require("groq-sdk")
const { z } = require("zod")
const chromium = require("@sparticuz/chromium")
const puppeteer = require("puppeteer-core")

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
    const prompt = `
You are a JSON API.

Return ONLY valid JSON.
Do not return explanation.
Do not return markdown.
Do not return candidate summary fields like candidate_name, role_applied_for, recommendation, candidate_score.
Generate EXACTLY 5 technical questions and EXACTLY 5 behavioral questions. Do not generate fewer than 5 in each section.
Generate a preparation plan covering EXACTLY 7 days. Do not generate fewer than 7 days in the preparationPlan array.
Use a clean, modern, professional design with a single accent color (like navy blue or dark teal) for headings and section dividers. Use proper spacing, a clear visual hierarchy, and avoid cluttered or overly colorful styling. The layout should look like a premium resume template, similar to ones used on LinkedIn or Canva.

You must return EXACTLY this structure:

{
  "title": "string",
  "matchScore": 0,
  "technicalQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "skillGaps": [
    {
      "skill": "string",
      "severity": "low"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focus": "string",
      "tasks": ["string"]
    }
  ]
}

Generate the response using this data:

Resume:
${resume.slice(0, 3000)}

Self Description:
${selfDescription.slice(0, 1000)}

Job Description:
${jobDescription.slice(0, 2000)}
`

    const response = await groq.chat.completions.create({
        model: "llama-3.3-70b-versatile",
        messages: [{ role: "user", content: prompt }],
        response_format: { type: "json_object" }
    })

    const rawText = response.choices[0].message.content

    console.log("RAW:", rawText)

    const parsedResponse = JSON.parse(rawText)

    if (
        !parsedResponse.title ||
        !Array.isArray(parsedResponse.technicalQuestions) ||
        !Array.isArray(parsedResponse.behavioralQuestions) ||
        !Array.isArray(parsedResponse.skillGaps) ||
        !Array.isArray(parsedResponse.preparationPlan)
    ) {
        throw new Error("AI returned wrong format")
    }

    return parsedResponse
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch({
        args: chromium.args,
        executablePath: await chromium.executablePath(),
        headless: chromium.headless,
    })
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        Return ONLY a valid JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await groq.chat.completions.create({
        model: "llama-3.3-70b-versatile",
        messages: [{ role: "user", content: prompt }],
        response_format: { type: "json_object" }
    })

    const jsonContent = JSON.parse(response.choices[0].message.content)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}

module.exports = { generateInterviewReport, generateResumePdf }